// PLAN §6.3 decision cards, v1 set (52). No card scolds the player; every option shows gain / cost.
// Effect notes for the engine:
//   - modifiers.value is a multiplier, except kind 'morale' where it is an additive morale-target bonus.
//   - cashPercent stays within ±0.25 here; engine caps again.
//   - Flags set by cards: rushedProject, starHire, vcHeavy, bootstrapLean, nichePath, platformPath,
//     bridgeLoan, emergencyLoan (engine may turn the loan flags into finance.debt).
//   - Rival cards read flags.rivalPressure (0–1), maintained by the engine.
import type { GameState, ModifierKind } from '../engine/types'
import type { DecisionCard } from './types'

const mod = (kind: ModifierKind, value: number, days: number) => ({ kind, value, days })
const rivalPressure = (s: GameState): number => {
  const v = s.flags['rivalPressure']
  return typeof v === 'number' ? v : 0
}

export const DECISIONS: readonly DecisionCard[] = [
  // =========================================================== Garaj (7)
  {
    id: 'early-focus',
    stage: 0,
    maxStage: 1,
    category: 'normal',
    speaker: 'cofounder',
    question: 'İki fikir birden cazip geliyor. Hangisine odaklanalım?',
    options: [
      {
        label: 'Tek ürüne odaklan',
        tradeoff: { gain: 'Proje hızı artar', cost: 'Diğer fikir bekler' },
        effects: { modifiers: [mod('production', 1.15, 30)] },
        reflection: 'Odak, erken aşamanın en ucuz hızlandırıcısıdır.',
        conceptId: 'focus',
      },
      {
        label: 'İkisini birden dene',
        tradeoff: { gain: 'Daha çok seçenek', cost: 'Her iş biraz yavaşlar' },
        effects: { reputation: 2, modifiers: [mod('production', 0.9, 20)] },
        reflection: 'Denemek öğretir, ama hız bölünür.',
        conceptId: 'focus',
      },
    ],
  },
  {
    id: 'early-channel',
    stage: 0,
    maxStage: 1,
    category: 'normal',
    speaker: 'mentor',
    question: 'İlk kullanıcıları nereden bulacağız? Bir kanal seçmen lazım.',
    options: [
      {
        label: 'Topluluklarda tek tek konuş',
        tradeoff: { gain: 'Sadık kullanıcı, düşük churn', cost: 'Kurucu enerjisi' },
        effects: { users: 8, energy: -15, modifiers: [mod('churn', 0.85, 30)] },
        reflection: 'Tek tek kazanılan kullanıcı, ürünü en iyi anlatandır.',
        conceptId: 'dont-scale',
      },
      {
        label: 'Küçük bir reklam dene',
        tradeoff: { gain: 'Hızlı ziyaretçi', cost: '$600 ve çabuk giden kullanıcı' },
        effects: { cash: -600, users: 25, modifiers: [mod('churn', 1.2, 30)] },
        reflection: 'Reklam kapıyı açar, kalmalarını ürün sağlar.',
        conceptId: 'pmf',
      },
    ],
  },
  {
    id: 'early-sidegig',
    stage: 0,
    maxStage: 1,
    category: 'normal',
    speaker: 'cofounder',
    question: 'Bir ajans serbest iş teklif ediyor. Kasa rahatlar ama zaman gider.',
    options: [
      {
        label: 'İşi al',
        tradeoff: { gain: '+$3K kasa', cost: 'Ürün 20 gün yavaşlar' },
        effects: { cash: 3000, modifiers: [mod('production', 0.8, 20)] },
        reflection: 'Runway satın almak bazen en akıllıca yatırımdır.',
        conceptId: 'runway',
      },
      {
        label: 'Ürüne odaklan',
        tradeoff: { gain: 'Tam hız ürün', cost: 'Kasa aynı kalır' },
        effects: { morale: 3, maturity: 0.03 },
        reflection: 'Zamanını ürüne vermek de bir yatırım.',
        conceptId: 'focus',
      },
    ],
  },
  {
    id: 'early-burnout',
    stage: 0,
    maxStage: 1,
    category: 'normal',
    speaker: 'cofounder',
    question: 'Haftalardır gece yarısına kadar çalışıyorsun. Biraz dinlensen mi?',
    condition: (s) => s.founder.energy < 60,
    options: [
      {
        label: 'İki gün dinlen',
        tradeoff: { gain: 'Enerji dolar', cost: 'İş iki gün yavaşlar' },
        effects: { energy: 40, modifiers: [mod('production', 0.85, 3)] },
        reflection: 'Dinlenmiş kurucu daha iyi karar verir.',
        conceptId: 'founder-burnout',
      },
      {
        label: 'Devam et',
        tradeoff: { gain: 'Hız korunur', cost: 'Enerji daha da düşer' },
        effects: { energy: -15, maturity: 0.03 },
        delayed: { days: 14, effects: { morale: -5 }, note: 'Yorgunluk ekibe de yansıdı.' },
        reflection: 'Tempo bir süre taşır, sonra faturasını keser.',
        conceptId: 'founder-burnout',
      },
    ],
  },
  {
    id: 'early-feedback',
    stage: 0,
    maxStage: 1,
    category: 'normal',
    speaker: 'customer',
    question: 'İlk kullanıcılardan biri ürünü sert eleştirdi. Ne yapalım?',
    options: [
      {
        label: 'Görüntülü görüşme ayarla',
        tradeoff: { gain: 'Ürün olgunlaşır', cost: 'Kurucu enerjisi' },
        effects: { maturity: 0.05, energy: -10 },
        reflection: 'Sert eleştiri, bedava danışmanlıktır.',
        conceptId: 'pmf',
      },
      {
        label: 'Teşekkür et, listeye ekle',
        tradeoff: { gain: 'Zaman kaybı yok', cost: 'İçgörü yüzeyde kalır' },
        effects: { reputation: 2 },
        reflection: 'Her geri bildirim aynı derinlikte dinlenemez.',
        conceptId: 'pmf',
      },
    ],
  },
  {
    id: 'early-equity-split',
    stage: 0,
    maxStage: 1,
    category: 'normal',
    speaker: 'cofounder',
    question: 'Ortaklık paylarını netleştirelim mi? Belirsizlik ileride dert olur.',
    options: [
      {
        label: 'Adil böl, hakediş ekle',
        tradeoff: { gain: 'Güven ve moral', cost: 'Hissenden %10' },
        effects: { equity: -0.1, morale: 8 },
        reflection: 'Net anlaşma, zor günlerde ortaklığı korur.',
        conceptId: 'dilution',
      },
      {
        label: 'Şimdilik konuşmayalım',
        tradeoff: { gain: 'Hisse sende kalır', cost: 'Belirsizlik birikir' },
        effects: {},
        delayed: { days: 45, effects: { morale: -8 }, note: 'Pay konusu gerginlik yarattı.' },
        reflection: 'Ertelenen konuşma genelde daha zor bir anda gelir.',
        conceptId: 'dilution',
      },
    ],
  },
  {
    id: 'friends-family',
    stage: 0,
    maxStage: 1,
    category: 'normal',
    speaker: 'mentor',
    question: 'Ailen ve arkadaşların küçük bir destek teklif ediyor. Alalım mı?',
    options: [
      {
        label: 'Kabul et',
        tradeoff: { gain: '+$8K kasa', cost: '%3 hisse ve ilişki baskısı' },
        effects: { cash: 8000, equity: -0.03 },
        reflection: 'Yakınlardan gelen para da bir sözleşmedir.',
        conceptId: 'dilution',
      },
      {
        label: 'Nazikçe reddet',
        tradeoff: { gain: 'Hisse ve ilişki korunur', cost: 'Kasa aynı kalır' },
        effects: { morale: 2 },
        reflection: 'Daha kısa runway, daha az yük demek olabilir.',
        conceptId: 'runway',
      },
    ],
  },

  // =========================================================== Pre-seed (7)
  {
    id: 'angel-1',
    stage: 1,
    maxStage: 2,
    category: 'normal',
    speaker: 'investor',
    question: 'Bir melek yatırımcı SAFE ile $40K koymak istiyor. Değerlemeyi sonraki tura bırakıyor.',
    options: [
      {
        label: "SAFE'i imzala",
        tradeoff: { gain: '+$40K kasa', cost: 'Sonraki turda ek dilution' },
        effects: { cash: 40_000, queueConcept: 'safe' },
        delayed: { days: 90, effects: { equity: -0.04 }, note: 'SAFE hisseye dönüştü.' },
        reflection: 'Bugünün kolay parası, yarının hisse tablosunda görünür.',
        conceptId: 'safe',
      },
      {
        label: 'Teşekkür et, bekle',
        tradeoff: { gain: 'Hisse korunur', cost: 'Kasa aynı kalır' },
        effects: { reputation: 2 },
        reflection: 'Beklemek de bir müzakere pozisyonudur.',
        conceptId: 'safe',
      },
    ],
  },
  {
    id: 'accelerator-invite',
    stage: 1,
    maxStage: 2,
    category: 'normal',
    speaker: 'mentor',
    question: 'Bir hızlandırıcı programdan davet geldi. Mentorluk ve ağ var, karşılığı %6 hisse.',
    options: [
      {
        label: 'Katıl',
        tradeoff: { gain: '+$25K, itibar, daha hızlı tur', cost: '%6 hisse' },
        effects: { cash: 25_000, equity: -0.06, reputation: 8, modifiers: [mod('roundSpeed', 1.2, 90)] },
        reflection: 'Ağ, hisseyle ödenen bir hızlandırıcıdır.',
        conceptId: 'dilution',
      },
      {
        label: 'Kendi yolumuza devam',
        tradeoff: { gain: 'Hisse ve odak sende', cost: 'Ağ ve mentorluk yok' },
        effects: { morale: 3, setFlag: 'bootstrapLean' },
        reflection: 'Bağımsızlık yavaş ama sağlam bir patikadır.',
        conceptId: 'default-alive',
      },
    ],
  },
  {
    id: 'grant-opportunity',
    stage: 1,
    maxStage: 2,
    category: 'normal',
    speaker: 'accountant',
    question: 'Ar-Ge hibesi başvurusu açıldı. Dosya hazırlamak iki hafta sürer.',
    options: [
      {
        label: 'Başvur',
        tradeoff: { gain: '2 ay sonra +$30K', cost: 'İki hafta yavaş ürün' },
        effects: { modifiers: [mod('production', 0.85, 14)] },
        delayed: { days: 60, effects: { cash: 30_000 }, note: 'Hibe onaylandı: +$30K.' },
        reflection: 'Hisse vermeyen para, sabır ister.',
        conceptId: 'runway',
      },
      {
        label: 'Ürüne odaklan',
        tradeoff: { gain: 'Hız korunur', cost: 'Bedava para kaçar' },
        effects: { maturity: 0.03 },
        reflection: 'Her fırsat, odaktan daha değerli değildir.',
        conceptId: 'focus',
      },
    ],
  },
  {
    id: 'key-hire',
    stage: 1,
    maxStage: 2,
    category: 'normal',
    speaker: 'cofounder',
    question: 'Çok iyi bir mühendis ilgileniyor ama maaşı bütçenin üstünde. Ne dersin?',
    options: [
      {
        label: 'Hisse opsiyonuyla al',
        tradeoff: { gain: 'Güçlü ekip, hızlı ürün', cost: '%2 hisse' },
        effects: { equity: -0.02, modifiers: [mod('production', 1.15, 60)] },
        reflection: 'Doğru kişi, hisseyi değerli kılar.',
        conceptId: 'hire-bar',
      },
      {
        label: 'Bütçeye sadık kal',
        tradeoff: { gain: 'Burn sabit kalır', cost: 'Bu yetenek kaçar' },
        effects: { morale: 1 },
        reflection: 'Disiplinli bütçe de bir strateji.',
        conceptId: 'burn',
      },
    ],
  },
  {
    id: 'cofounder-conflict',
    stage: 1,
    maxStage: 2,
    category: 'normal',
    speaker: 'cofounder',
    question: 'Ortağınla yön konusunda anlaşamıyorsunuz. Gerilim ekibe de yansıyor.',
    options: [
      {
        label: 'Açık bir toplantı yap',
        tradeoff: { gain: 'Moral toparlanır', cost: 'Enerji ve iki gün' },
        effects: { morale: 8, energy: -20 },
        reflection: 'Konuşulan anlaşmazlık, büyümeden çözülür.',
        conceptId: 'morale-compounds',
      },
      {
        label: 'Kararı sen ver, devam et',
        tradeoff: { gain: 'Hız korunur', cost: 'Gerilim bir ay sürer' },
        effects: { modifiers: [mod('morale', -6, 30)] },
        reflection: 'Hızlı karar zaman kazandırır, gerilimi taşır.',
        conceptId: 'morale-compounds',
      },
      {
        label: 'Mentordan arabuluculuk iste',
        tradeoff: { gain: 'Tarafsız bir göz', cost: '$2K ve %1 hisse' },
        effects: { cash: -2000, equity: -0.01, morale: 5 },
        reflection: 'Dışarıdan bakış, içeride görünmeyeni gösterir.',
        conceptId: 'morale-compounds',
      },
    ],
  },
  {
    id: 'advisor-equity',
    stage: 1,
    maxStage: 2,
    category: 'normal',
    speaker: 'mentor',
    question: 'Tanınmış bir isim danışmanın olmak istiyor. Karşılığında %2 hisse istiyor.',
    options: [
      {
        label: 'Kabul et',
        tradeoff: { gain: 'İtibar ve daha hızlı tur', cost: '%2 hisse' },
        effects: { equity: -0.02, reputation: 10, modifiers: [mod('roundSpeed', 1.15, 120)] },
        reflection: 'Doğru isim kapıları açar, hisse de kalıcıdır.',
        conceptId: 'dilution',
      },
      {
        label: 'Ücretli danışmanlık öner',
        tradeoff: { gain: 'Hisse korunur', cost: '$1.5K nakit' },
        effects: { cash: -1500, reputation: 4 },
        reflection: 'Nakit pahalı ama hisseden ucuz olabilir.',
        conceptId: 'dilution',
      },
    ],
  },
  {
    id: 'pmf-hypothesis-width',
    stage: 1,
    maxStage: 2,
    category: 'normal',
    speaker: 'customer',
    question: 'Kitleyi geniş mi tutalım, dar bir niş mi? İkisi farklı ürün demek.',
    options: [
      {
        label: 'Dar bir niş seç',
        tradeoff: { gain: 'Hızlı olgunluk, düşük churn', cost: 'Küçük pazar' },
        effects: {
          maturity: 0.06,
          setFlag: 'nichePath',
          modifiers: [mod('churn', 0.85, 60), mod('organic', 0.85, 60)],
        },
        reflection: 'Küçük bir kitleyi çok mutlu etmek sağlam bir başlangıç.',
        conceptId: 'pmf',
      },
      {
        label: 'Geniş kitleye aç',
        tradeoff: { gain: 'Büyük pazar, daha çok kullanıcı', cost: 'Ürün yavaş oturur' },
        effects: { setFlag: 'platformPath', modifiers: [mod('organic', 1.2, 60), mod('churn', 1.15, 60)] },
        reflection: 'Geniş ağ çok balık tutar, bazıları kaçar.',
        conceptId: 'pmf',
      },
    ],
  },

  // =========================================================== Seed (10)
  {
    id: 'seed-termsheet',
    stage: 2,
    maxStage: 3,
    category: 'normal',
    speaker: 'investor',
    question: 'Term sheet geldi, bir de yönetim kurulu gözlemcisi istiyorlar.',
    condition: (s) => s.round?.active === true,
    options: [
      {
        label: 'Gözlemciyi kabul et',
        tradeoff: { gain: 'Tur 2 hafta hızlanır', cost: 'Kararlarda şeffaflık baskısı' },
        effects: { roundWeeks: -2, reputation: 3 },
        reflection: 'Şeffaflık, güvenin para birimidir.',
        conceptId: 'fundraise-time',
      },
      {
        label: 'Sadece parayı konuş',
        tradeoff: { gain: 'Kontrol sende', cost: 'Tur 1 hafta uzar' },
        effects: { roundWeeks: 1 },
        reflection: 'Kontrolü korumak zaman alabilir.',
        conceptId: 'fundraise-time',
      },
    ],
  },
  {
    id: 'press-launch',
    stage: 2,
    maxStage: 3,
    category: 'normal',
    speaker: 'journalist',
    question: 'Bir teknoloji sitesi haber yapmak istiyor. Lansmanı şimdi mi duyuralım?',
    options: [
      {
        label: 'Hemen duyur',
        tradeoff: { gain: 'Kullanıcı dalgası', cost: 'Sunucu ve churn riski' },
        effects: { users: 100, usersPercent: 0.2, reputation: 6, modifiers: [mod('churn', 1.2, 30)] },
        reflection: 'Haber kullanıcı getirir, kalmalarını ürün sağlar.',
        conceptId: 'churn',
      },
      {
        label: 'Ürün oturunca',
        tradeoff: { gain: 'Kalıcı kullanıcı', cost: 'İlgi soğuyabilir' },
        effects: {},
        delayed: { days: 30, effects: { users: 60, reputation: 4 }, note: 'Ertelenen haber yayında.' },
        reflection: 'Doğru zamanlama, haberin ömrünü uzatır.',
        conceptId: 'pmf',
      },
    ],
  },
  {
    id: 'negative-review',
    stage: 2,
    maxStage: 3,
    category: 'normal',
    speaker: 'journalist',
    question: 'Popüler bir forumda ürün hakkında sert bir yorum yayılıyor.',
    options: [
      {
        label: 'Açıkça yanıtla ve düzelt',
        tradeoff: { gain: 'İtibar toparlanır', cost: 'Ekip bir hafta buna döner' },
        effects: { reputation: 4, modifiers: [mod('production', 0.85, 7), mod('churn', 0.95, 30)] },
        reflection: 'Açık yanıt, eleştireni bile savunucuya çevirebilir.',
        conceptId: 'churn',
      },
      {
        label: 'Yorum yapma, işine bak',
        tradeoff: { gain: 'Odak bozulmaz', cost: 'İtibar biraz düşer' },
        effects: { reputation: -5 },
        reflection: 'Sessizlik de bir mesajdır, herkes aynı okumaz.',
        conceptId: 'churn',
      },
    ],
  },
  {
    id: 'pricing-change',
    stage: 2,
    maxStage: 3,
    category: 'normal',
    speaker: 'accountant',
    question: 'Fiyatı %20 artırmayı düşünüyoruz. Bazı kullanıcılar gidebilir.',
    options: [
      {
        label: 'Herkes için artır',
        tradeoff: { gain: 'Gelir hızla artar', cost: 'Bir ay churn yükselir' },
        effects: { modifiers: [mod('arpu', 1.15, 90), mod('churn', 1.15, 30)] },
        reflection: 'Kalanlar, ürüne gerçekten değer verenlerdir.',
        conceptId: 'pricing',
      },
      {
        label: 'Sadece yeni kullanıcılara',
        tradeoff: { gain: 'Mevcut kullanıcı kalır', cost: 'Gelir yavaş artar' },
        effects: { modifiers: [mod('arpu', 1.07, 90)] },
        reflection: 'Yumuşak geçiş, güveni korur.',
        conceptId: 'pricing',
      },
    ],
  },
  {
    id: 'feature-request-flood',
    stage: 2,
    maxStage: 3,
    category: 'normal',
    speaker: 'customer',
    question: 'Kullanıcılar onlarca özellik istiyor. Hepsine yetişemeyiz.',
    options: [
      {
        label: 'En çok isteneni yap',
        tradeoff: { gain: 'Kullanıcı memnuniyeti', cost: 'Yol haritası kayar' },
        effects: { maturity: 0.02, modifiers: [mod('churn', 0.9, 45)] },
        reflection: 'Dinlemek iyidir, her isteği ürün yapmak şart değil.',
        conceptId: 'feature-vs-product',
      },
      {
        label: 'Vizyona sadık kal',
        tradeoff: { gain: 'Ürün tutarlı kalır', cost: 'Bazı kullanıcılar küser' },
        effects: { maturity: 0.05, modifiers: [mod('churn', 1.05, 30)] },
        reflection: 'Net bir vizyon, bazı hayırlar gerektirir.',
        conceptId: 'feature-vs-product',
      },
    ],
  },
  {
    id: 'remote-vs-office',
    stage: 2,
    maxStage: 3,
    category: 'normal',
    speaker: 'cofounder',
    question: 'Ekip uzaktan çalışmak istiyor. Ofis mi, hibrit mi?',
    options: [
      {
        label: 'Hibrit çalışalım',
        tradeoff: { gain: 'Moral artar', cost: 'Koordinasyon zorlaşır' },
        effects: { morale: 6, modifiers: [mod('production', 0.95, 30)] },
        reflection: 'Esneklik, güvenle birlikte çalışır.',
        conceptId: 'culture-freezes',
      },
      {
        label: 'Ofiste kalalım',
        tradeoff: { gain: 'Hızlı iletişim', cost: 'Bazıları mutsuz' },
        effects: { morale: -4, modifiers: [mod('production', 1.05, 30)] },
        reflection: 'Yakınlık hız verir, herkese aynı uymaz.',
        conceptId: 'culture-freezes',
      },
    ],
  },
  {
    id: 'culture-values',
    stage: 2,
    maxStage: 3,
    category: 'normal',
    speaker: 'cofounder',
    question: 'Şirket değerlerini yazıya dökmenin zamanı geldi mi?',
    options: [
      {
        label: 'Ekiple birlikte yazalım',
        tradeoff: { gain: 'Uzun süreli moral bonusu', cost: 'Bir haftalık odak' },
        effects: { morale: 5, modifiers: [mod('morale', 3, 120), mod('production', 0.9, 7)] },
        reflection: 'Yazılı değerler, yeni gelenlere pusula olur.',
        conceptId: 'culture-freezes',
      },
      {
        label: 'Şimdi değil',
        tradeoff: { gain: 'Hız korunur', cost: 'Kültür kendi kendine şekillenir' },
        effects: {},
        delayed: { days: 60, effects: { morale: -4 }, note: 'Ekipte "biz kimiz?" sorusu dolaşıyor.' },
        reflection: 'Kültür yazılmasa da oluşur, sadece kendi yolunu seçer.',
        conceptId: 'culture-freezes',
      },
    ],
  },
  {
    id: 'hiring-bar-vs-speed',
    stage: 2,
    maxStage: 3,
    category: 'normal',
    speaker: 'cofounder',
    question: 'Açık pozisyonlar bekliyor. Çıtayı düşürüp hızlı mı alalım?',
    options: [
      {
        label: 'Hızlı al',
        tradeoff: { gain: 'Ekip hızla büyür', cost: 'Kalite ve moral riski' },
        effects: { modifiers: [mod('production', 1.1, 30)] },
        delayed: { days: 45, effects: { morale: -6 }, note: 'Aceleyle kurulan ekipte uyum sorunu çıktı.' },
        reflection: 'Hız bugün kazandırır, uyum yarın sorulur.',
        conceptId: 'hire-bar',
      },
      {
        label: 'Çıtayı koru',
        tradeoff: { gain: 'Güçlü ve uyumlu ekip', cost: 'Büyüme yavaşlar' },
        effects: { morale: 4, modifiers: [mod('production', 0.95, 30)] },
        reflection: 'Doğru kişiyi beklemek, yanlışı çıkarmaktan kolaydır.',
        conceptId: 'hire-bar',
      },
    ],
  },
  {
    id: 'd7-retention-drop',
    stage: 2,
    maxStage: 3,
    category: 'normal',
    speaker: 'engineer',
    question: 'Yeni kullanıcıların çoğu ilk haftada bırakıyor. Karşılama akışı mı sorunlu?',
    condition: (s) => s.stats.users > 200,
    options: [
      {
        label: 'Karşılamayı yeniden tasarla',
        tradeoff: { gain: 'Tutunma belirgin artar', cost: 'İki hafta yeni özellik yok' },
        effects: { modifiers: [mod('churn', 0.8, 60), mod('production', 0.9, 14)] },
        reflection: 'İlk hafta, kullanıcının kalıp kalmayacağına karar verdiği yerdir.',
        conceptId: 'churn',
      },
      {
        label: 'Hatırlatma e-postası ekle',
        tradeoff: { gain: 'Hızlı ve ucuz', cost: 'Etkisi sınırlı' },
        effects: { modifiers: [mod('churn', 0.93, 30)] },
        reflection: 'Küçük dokunuşlar da bir şeyleri değiştirir.',
        conceptId: 'churn',
      },
    ],
  },
  {
    id: 'server-crash',
    stage: 2,
    maxStage: 3,
    category: 'normal',
    speaker: 'engineer',
    question: 'Sunucular çöktü, kullanıcılar bekliyor. Nasıl ilerleyelim?',
    condition: (s) => s.derived.overload > 0 || s.stats.users > 1000,
    options: [
      {
        label: 'Gece boyu yama yap',
        tradeoff: { gain: 'Hızlı geri dönüş', cost: 'Yorgunluk ve teknik borç' },
        effects: { morale: -5, techDebt: 5 },
        reflection: 'Yama bugünü kurtarır, borcu yarına yazar.',
        conceptId: 'tech-debt',
      },
      {
        label: 'Durum sayfası aç, sağlam çöz',
        tradeoff: { gain: 'Kalıcı çözüm, güven', cost: 'Biraz kullanıcı kaybı' },
        effects: { usersPercent: -0.03, reputation: 2 },
        reflection: 'Şeffaf kesinti, sessiz kesintiden çok daha az iz bırakır.',
        conceptId: 'tech-debt',
      },
    ],
  },

  // =========================================================== Series A (10)
  {
    id: 'vc-board-seat',
    stage: 3,
    maxStage: 4,
    category: 'normal',
    speaker: 'investor',
    question: 'Yatırımcı yönetim kurulunda koltuk istiyor.',
    options: [
      {
        label: 'Koltuğu ver',
        tradeoff: { gain: 'Ağ, deneyim, hızlı turlar', cost: 'Kontrol paylaşılır' },
        effects: { reputation: 6, setFlag: 'vcHeavy', modifiers: [mod('roundSpeed', 1.2, 180)] },
        reflection: 'Yönetim kurulu hem ayna hem direksiyondur.',
        conceptId: 'cap-table-health',
      },
      {
        label: 'Gözlemci statüsü öner',
        tradeoff: { gain: 'Kontrol sende', cost: 'İlişki biraz soğur' },
        effects: { reputation: -2 },
        reflection: 'Kontrolü korumak da meşru bir tercihtir.',
        conceptId: 'cap-table-health',
      },
    ],
  },
  {
    id: 'ad-spend-temptation',
    stage: 3,
    maxStage: 4,
    category: 'normal',
    speaker: 'mentor',
    question: 'Reklam bütçesini ikiye katlarsak büyüme uçacak gibi görünüyor.',
    options: [
      {
        label: 'İkiye katla',
        tradeoff: { gain: 'Hızlı kullanıcı artışı', cost: 'Kasa hızla erir' },
        effects: { cashPercent: -0.08, usersPercent: 0.15, modifiers: [mod('churn', 1.1, 30)] },
        reflection: 'Reklam hızlandırır, ekonomisi tutarsa.',
        conceptId: 'ltv-cac',
      },
      {
        label: "Önce LTV:CAC'a bak",
        tradeoff: { gain: 'Para boşa gitmez', cost: 'Büyüme yavaş' },
        effects: { queueConcept: 'ltv-cac', modifiers: [mod('organic', 1.05, 30)] },
        reflection: 'Hesabı önce yapmak, sonra düzeltmekten ucuzdur.',
        conceptId: 'ltv-cac',
      },
    ],
  },
  {
    id: 'growth-hack',
    stage: 3,
    maxStage: 4,
    category: 'normal',
    speaker: 'engineer',
    question: 'Bir büyüme hilesi buldum: davet edene ödül. Hızlı ama sınırda.',
    options: [
      {
        label: 'Hemen dene',
        tradeoff: { gain: 'Hızlı kullanıcı', cost: 'Kalitesiz kullanıcı, churn' },
        effects: { usersPercent: 0.12, modifiers: [mod('churn', 1.2, 45)] },
        reflection: 'Hızlı gelen kullanıcı, hızlı gidebilir.',
        conceptId: 'organic-vs-paid',
      },
      {
        label: 'Referans programını düzgün kur',
        tradeoff: { gain: 'Kalıcı organik büyüme', cost: 'Bir ay sürer' },
        effects: {},
        delayed: { days: 30, effects: { modifiers: [mod('organic', 1.2, 90)] }, note: 'Referans programı yayında.' },
        reflection: 'Kullanıcının kullanıcı getirmesi, en sağlam kanaldır.',
        conceptId: 'organic-vs-paid',
      },
    ],
  },
  {
    id: 'viral-tiktok',
    stage: 3,
    maxStage: 4,
    category: 'normal',
    speaker: 'journalist',
    question: 'Bir videomuz viral oldu! Sunucular zorlanmaya başladı.',
    options: [
      {
        label: 'Anı yakala, kapasite kirala',
        tradeoff: { gain: 'Büyük kullanıcı dalgası', cost: 'Altyapı faturası' },
        effects: { cashPercent: -0.05, usersPercent: 0.25, reputation: 5 },
        reflection: 'Şans hazırlıklı olana uğrar, faturası da gelir.',
        conceptId: 'organic-vs-paid',
      },
      {
        label: 'Bekleme listesi aç',
        tradeoff: { gain: 'Merak ve kalite', cost: 'Bazıları vazgeçer' },
        effects: { usersPercent: 0.1, reputation: 8 },
        reflection: 'Kıtlık da bir pazarlama dilidir.',
        conceptId: 'organic-vs-paid',
      },
    ],
  },
  {
    id: 'technical-debt-vote',
    stage: 3,
    maxStage: 4,
    category: 'normal',
    speaker: 'engineer',
    question: 'Ekip bir sprinti sadece teknik borca ayırmak istiyor.',
    options: [
      {
        label: 'Evet, temizleyelim',
        tradeoff: { gain: 'Borç azalır, hız geri gelir', cost: 'Bir ay yeni özellik yok' },
        effects: { techDebt: -20, modifiers: [mod('production', 0.8, 30)] },
        delayed: { days: 30, effects: { modifiers: [mod('production', 1.1, 60)] }, note: 'Temiz kod, ekibi hızlandırdı.' },
        reflection: 'Borcu ödemek, gelecekteki hızı satın almaktır.',
        conceptId: 'tech-debt',
      },
      {
        label: 'Önce yeni özellik',
        tradeoff: { gain: 'Yol haritası ilerler', cost: 'Borç faizle birikir' },
        effects: { techDebt: 10, maturity: 0.03, setFlag: 'rushedProject' },
        reflection: 'Bazen hız borca değer, faizini bilmek şartıyla.',
        conceptId: 'tech-debt',
      },
    ],
  },
  {
    id: 'star-resign',
    stage: 3,
    maxStage: 4,
    category: 'normal',
    speaker: 'cofounder',
    question: 'Yıldız çalışanımız rakipten teklif almış. Kalması için ne yapalım?',
    condition: (s) => s.derived.teamSize >= 8,
    options: [
      {
        label: 'Karşı teklif ver',
        tradeoff: { gain: 'O kalır', cost: 'Maaş dengesi bozulur' },
        effects: { cashPercent: -0.04, morale: -3, setFlag: 'starHire' },
        reflection: 'Bir kişiyi tutmak, diğerlerine de bir mesajdır.',
        conceptId: 'ten-x-myth',
      },
      {
        label: 'Bilgiyi yay, gitmesine izin ver',
        tradeoff: { gain: 'Sistem güçlenir', cost: 'Kısa süre yavaşlama' },
        effects: { modifiers: [mod('production', 0.85, 30)] },
        delayed: { days: 45, effects: { modifiers: [mod('production', 1.1, 60)] }, note: 'Ekip bilgiyi paylaşınca hızlandı.' },
        reflection: 'Kişiye değil sisteme yatırım, uzun vadede taşır.',
        conceptId: 'ten-x-myth',
      },
    ],
  },
  {
    id: 'crunch-vs-launch',
    stage: 3,
    maxStage: 4,
    category: 'normal',
    speaker: 'cofounder',
    question: 'Lansmana iki hafta var ve yetişmeyecek. Crunch mı, erteleme mi?',
    options: [
      {
        label: 'Crunch yap',
        tradeoff: { gain: 'Lansman zamanında', cost: 'Moral ve teknik borç' },
        effects: { morale: -8, techDebt: 8, maturity: 0.05, setFlag: ['crunch', 'rushedProject'] },
        reflection: 'Crunch bir kez işe yarar, alışkanlık olursa yorar.',
        conceptId: 'tech-debt',
      },
      {
        label: 'İki hafta ertele',
        tradeoff: { gain: 'Ekip dinlenir, kalite artar', cost: 'Basın ilgisi soğur' },
        effects: { reputation: -3, morale: 3, maturity: 0.02 },
        reflection: 'Ertelenen tarih unutulur, kötü lansman hatırlanır.',
        conceptId: 'tech-debt',
      },
    ],
  },
  {
    id: 'b2b-opportunity',
    stage: 3,
    maxStage: 4,
    category: 'normal',
    speaker: 'customer',
    question: 'Büyük bir şirket ürünümüzü kurumsal olarak kullanmak istiyor.',
    options: [
      {
        label: 'Anlaş',
        tradeoff: { gain: 'Büyük, düzenli gelir', cost: 'Özel talepler gelecek' },
        effects: { cashPercent: 0.1, queueCard: 'custom-feature-trap' },
        reflection: 'Büyük müşteri büyük gelir, büyük beklenti getirir.',
        conceptId: 'concentration',
      },
      {
        label: 'Bireysel kullanıcıya odaklan',
        tradeoff: { gain: 'Ürün sade kalır', cost: 'Büyük gelir kaçar' },
        effects: { morale: 2 },
        reflection: 'Odak bazen para bırakmak demektir.',
        conceptId: 'focus',
      },
    ],
  },
  {
    id: 'custom-feature-trap',
    stage: 3,
    maxStage: 5,
    category: 'normal',
    speaker: 'customer',
    question: 'Kurumsal müşteri sadece kendisi için bir özellik istiyor.',
    weight: 0.5,
    options: [
      {
        label: 'Olduğu gibi yap',
        tradeoff: { gain: 'Müşteri mutlu', cost: 'Ürün dağılır, borç birikir' },
        effects: { cashPercent: 0.05, techDebt: 6, modifiers: [mod('production', 0.9, 30)] },
        reflection: 'Tek müşteriye özel kod, herkesin bakım yüküdür.',
        conceptId: 'feature-vs-product',
      },
      {
        label: 'Herkese açık özellik yap',
        tradeoff: { gain: 'Tüm kullanıcılar faydalanır', cost: 'Müşteri bekler' },
        effects: { maturity: 0.03 },
        reflection: 'Özel isteği genel değere çevirmek bir ustalıktır.',
        conceptId: 'feature-vs-product',
      },
      {
        label: 'Nazikçe reddet',
        tradeoff: { gain: 'Odak korunur', cost: 'Müşteri gidebilir' },
        effects: { cashPercent: -0.03 },
        reflection: 'Hayır demek, ürünü korumanın bir yoludur.',
        conceptId: 'feature-vs-product',
      },
    ],
  },
  {
    id: 'blitzscale-pressure',
    stage: 3,
    maxStage: 4,
    category: 'normal',
    speaker: 'investor',
    question: 'Yatırımcılar "pazarı hemen kapla" diyor. Hızla büyümeli miyiz?',
    options: [
      {
        label: 'Gaza bas',
        tradeoff: { gain: 'Hızlı büyüme', cost: 'Burn ve kaos' },
        effects: { usersPercent: 0.15, cashPercent: -0.1, setFlag: 'vcHeavy', modifiers: [mod('morale', -4, 60)] },
        reflection: 'Hız pazarı kazandırabilir, kaosu da beraberinde getirir.',
        conceptId: 'premature-scaling',
      },
      {
        label: 'Sağlıklı tempoda büyü',
        tradeoff: { gain: 'Kontrollü büyüme', cost: 'Yatırımcı sabırsızlanır' },
        effects: { reputation: -2, morale: 3, setFlag: 'bootstrapLean' },
        reflection: 'Kendi temposunu bilen şirket, uzun koşar.',
        conceptId: 'premature-scaling',
      },
    ],
  },

  // =========================================================== Series B (7)
  {
    id: 'enterprise-rfp',
    stage: 4,
    maxStage: 5,
    category: 'normal',
    speaker: 'customer',
    question: 'Bir holding ihale açtı. Kazanmak aylar sürebilir.',
    options: [
      {
        label: 'Teklif hazırla',
        tradeoff: { gain: 'Büyük kurumsal müşteri', cost: 'Ekip bir ay meşgul' },
        effects: { modifiers: [mod('production', 0.9, 30)] },
        delayed: { days: 45, effects: { cashPercent: 0.1, reputation: 5 }, note: 'İhaleyi kazandık!' },
        reflection: 'Kurumsal satış sabır ister, sonra düzenli öder.',
        conceptId: 'compliance',
      },
      {
        label: 'Pas geç',
        tradeoff: { gain: 'Odak korunur', cost: 'Büyük fırsat kaçar' },
        effects: { morale: 1 },
        reflection: 'Her ihale kazanılmaya değmez.',
        conceptId: 'focus',
      },
    ],
  },
  {
    id: 'whale-churn',
    stage: 4,
    maxStage: 5,
    category: 'normal',
    speaker: 'accountant',
    question: 'En büyük müşterimiz sözleşmeyi yenilemeyebilir.',
    options: [
      {
        label: 'İndirimle tut',
        tradeoff: { gain: 'Gelir korunur', cost: 'Marj düşer' },
        effects: { modifiers: [mod('arpu', 0.95, 90)] },
        reflection: 'Tutmak kazanmaktan ucuzdur, bağımlılığı da uzatır.',
        conceptId: 'concentration',
      },
      {
        label: 'Riski dağıt, yeni müşteri ara',
        tradeoff: { gain: 'Bağımlılık azalır', cost: 'Kısa vadede gelir kaybı' },
        effects: { cashPercent: -0.05, modifiers: [mod('organic', 1.1, 60)] },
        reflection: 'Dağılmış gelir, rahat uyku demektir.',
        conceptId: 'concentration',
      },
    ],
  },
  {
    id: 'gdpr-audit',
    stage: 4,
    maxStage: 5,
    category: 'normal',
    speaker: 'accountant',
    question: 'Veri koruma denetimi kapıda. Hazır mıyız?',
    options: [
      {
        label: 'Danışman tut, hazırlan',
        tradeoff: { gain: 'Kurumsal kapı açılır', cost: 'Bütçeden pay' },
        effects: { cashPercent: -0.04, reputation: 6, queueConcept: 'compliance' },
        reflection: 'Uyum, görünmeyen bir satış ekibidir.',
        conceptId: 'compliance',
      },
      {
        label: 'Asgari hazırlıkla geç',
        tradeoff: { gain: 'Para kasada kalır', cost: 'Ceza riski' },
        effects: {},
        delayed: { days: 60, effects: { cashPercent: -0.08, reputation: -5 }, note: 'Denetimde eksikler çıktı.' },
        reflection: 'Uyumu ertelemek, faturayı ertelemektir.',
        conceptId: 'compliance',
      },
    ],
  },
  {
    id: 'cloud-bill-shock',
    stage: 4,
    maxStage: 5,
    category: 'normal',
    speaker: 'engineer',
    question: 'Bu ayki bulut faturası iki katına çıktı.',
    options: [
      {
        label: 'Optimizasyona ekip ayır',
        tradeoff: { gain: 'Altyapı ucuzlar', cost: 'Bir sprint gider' },
        effects: { modifiers: [mod('production', 0.9, 20)] },
        delayed: { days: 30, effects: { cashPercent: 0.03 }, note: 'Optimizasyon faturayı düşürdü.' },
        reflection: 'Görünmeyen gider, görünür hale gelince küçülür.',
        conceptId: 'burn',
      },
      {
        label: 'Öde, büyümeye devam',
        tradeoff: { gain: 'Hız korunur', cost: 'Kasa erir' },
        effects: { cashPercent: -0.05 },
        reflection: 'Büyümenin bir altyapı faturası vardır.',
        conceptId: 'burn',
      },
    ],
  },
  {
    id: 'talent-raid',
    stage: 4,
    maxStage: 5,
    category: 'normal',
    speaker: 'cofounder',
    question: 'Büyük bir teknoloji şirketi ekibimizden insan topluyor.',
    options: [
      {
        label: 'Maaşları artır',
        tradeoff: { gain: 'Ekip kalır', cost: 'Burn artar' },
        effects: { cashPercent: -0.05, morale: 6 },
        reflection: 'Para tutar, tek başına bağlamaz.',
        conceptId: 'morale-compounds',
      },
      {
        label: 'Hisse opsiyonu dağıt',
        tradeoff: { gain: 'Aidiyet artar', cost: 'Hissen azalır' },
        effects: { equity: -0.02, morale: 8 },
        reflection: 'Ortak gibi hisseden ekip, ortak gibi davranır.',
        conceptId: 'cap-table-health',
      },
      {
        label: 'Misyona güven',
        tradeoff: { gain: 'Ek maliyet yok', cost: 'Bazıları gidebilir' },
        effects: { morale: -5 },
        reflection: 'Misyon güçlüdür, rakip teklif de öyle.',
        conceptId: 'morale-compounds',
      },
    ],
  },
  {
    id: 'international-launch',
    stage: 4,
    maxStage: 5,
    category: 'normal',
    speaker: 'investor',
    question: 'Yurt dışına açılma zamanı mı? Yeni pazar, yeni dertler demek.',
    options: [
      {
        label: 'Yurt dışına açıl',
        tradeoff: { gain: 'Büyük yeni pazar', cost: 'Maliyet ve karmaşa' },
        effects: { cashPercent: -0.1, setFlag: 'platformPath', modifiers: [mod('production', 0.9, 45)] },
        delayed: { days: 60, effects: { usersPercent: 0.2 }, note: 'Yeni pazardan kullanıcılar geliyor.' },
        reflection: 'Yeni pazar, yeni bir şirket kurmak gibidir.',
        conceptId: 'focus',
      },
      {
        label: 'Ev pazarını derinleştir',
        tradeoff: { gain: 'Güçlü, sadık taban', cost: 'Büyüme tavanı' },
        effects: { setFlag: 'nichePath', modifiers: [mod('churn', 0.9, 90)] },
        reflection: 'Derin kök, rüzgârda devrilmez.',
        conceptId: 'focus',
      },
    ],
  },
  {
    id: 'market-downturn',
    stage: 4,
    maxStage: 5,
    category: 'normal',
    speaker: 'investor',
    question: 'Piyasa soğudu, yatırımcılar temkinli. Planı değiştirelim mi?',
    options: [
      {
        label: 'Tasarrufa geç',
        tradeoff: { gain: 'Runway uzar', cost: 'Büyüme ve moral düşer' },
        effects: { cashPercent: 0.05, morale: -4, modifiers: [mod('production', 0.9, 60)] },
        reflection: 'Soğuk piyasada hayatta kalan, sonra büyür.',
        conceptId: 'default-alive',
      },
      {
        label: 'Planında kal',
        tradeoff: { gain: 'Momentum korunur', cost: 'Sonraki tur zorlaşır' },
        effects: { modifiers: [mod('roundSpeed', 0.8, 90)] },
        reflection: 'Momentum değerlidir, runway ile birlikte.',
        conceptId: 'fundraise-time',
      },
    ],
  },

  // =========================================================== Series C (5)
  {
    id: 'acquisition-offer',
    stage: 5,
    category: 'normal',
    speaker: 'investor',
    question: 'Büyük bir şirket bizi satın almak istiyor. Rakam cazip.',
    options: [
      {
        label: 'Masaya otur, satma',
        tradeoff: { gain: 'Değerleme kanıtı, itibar', cost: 'Yönetim zamanı ve enerji' },
        effects: { reputation: 8, energy: -15 },
        reflection: 'Teklif almak, değerinin dışarıdan teyididir.',
        conceptId: 'no-single-path',
      },
      {
        label: 'Kapıyı nazikçe kapat',
        tradeoff: { gain: 'Odak ve moral', cost: 'Güvenli çıkış kaçar' },
        effects: { morale: 5 },
        reflection: 'Hedefi bilen, cazip teklife de hayır diyebilir.',
        conceptId: 'no-single-path',
      },
    ],
  },
  {
    id: 'strategic-investor',
    stage: 5,
    category: 'normal',
    speaker: 'investor',
    question: 'Sektörün devi stratejik yatırım yapmak istiyor.',
    options: [
      {
        label: 'Yatırımı al',
        tradeoff: { gain: 'Nakit ve dağıtım gücü', cost: '%3 hisse, rakipler çekinir' },
        effects: { cashPercent: 0.12, equity: -0.03, modifiers: [mod('organic', 1.2, 90)] },
        reflection: 'Stratejik para, stratejik bağ da getirir.',
        conceptId: 'concentration',
      },
      {
        label: 'Bağımsız kal',
        tradeoff: { gain: 'Tarafsızlık', cost: 'Ek para yok' },
        effects: { reputation: 3 },
        reflection: 'Tarafsız kalmak, herkesle çalışma özgürlüğüdür.',
        conceptId: 'concentration',
      },
    ],
  },
  {
    id: 'secondary-sale',
    stage: 5,
    category: 'normal',
    speaker: 'investor',
    question: 'Hissenin bir kısmını satıp kişisel olarak rahatlayabilirsin.',
    options: [
      {
        label: '%3 sat',
        tradeoff: { gain: 'Kişisel güvence ve enerji', cost: 'Hissen azalır' },
        effects: { equity: -0.03, energy: 30 },
        reflection: 'Rahat bir kurucu, uzun vadeli düşünebilir.',
        conceptId: 'cap-table-health',
      },
      {
        label: 'Tümünü tut',
        tradeoff: { gain: 'Tam pay sende', cost: 'Kişisel risk sürer' },
        effects: { energy: -5 },
        reflection: 'Tüm yumurtalar tek sepette, sepeti iyi tanıyorsan.',
        conceptId: 'cap-table-health',
      },
    ],
  },
  {
    id: 'founder-burnout',
    stage: 5,
    category: 'normal',
    speaker: 'cofounder',
    question: 'Aylardır izin yapmadın. Ekip senin için endişeli.',
    options: [
      {
        label: 'Bir hafta izin yap',
        tradeoff: { gain: 'Enerji ve bakış açısı', cost: 'Bir hafta sensiz' },
        effects: { energy: 50, modifiers: [mod('production', 0.9, 7)] },
        reflection: 'Şirket sensiz bir hafta dayanabiliyorsa, iyi kurmuşsun.',
        conceptId: 'founder-burnout',
      },
      {
        label: 'Yetki devret',
        tradeoff: { gain: 'Yük hafifler', cost: 'Bazı kararlar senden çıkar' },
        effects: { energy: 25, morale: 4 },
        reflection: 'Devretmek, ekibe güvenin görünür halidir.',
        conceptId: 'founder-burnout',
      },
      {
        label: 'Devam et',
        tradeoff: { gain: 'Hız korunur', cost: 'Tükenme riski' },
        effects: { energy: -10 },
        reflection: 'Maratonda da molalar vardır.',
        conceptId: 'founder-burnout',
      },
    ],
  },
  {
    id: 'ipo-vs-stay-private',
    stage: 5,
    category: 'normal',
    speaker: 'investor',
    question: 'Halka arz konuşulmaya başlandı. Hazır mıyız?',
    options: [
      {
        label: 'Hazırlık başlat',
        tradeoff: { gain: 'İtibar ve likidite yolu', cost: 'Uyum yükü ve maliyet' },
        effects: { reputation: 10, cashPercent: -0.05, modifiers: [mod('production', 0.95, 60)] },
        reflection: 'Halka arz bir varış değil, yeni bir başlangıçtır.',
        conceptId: 'compliance',
      },
      {
        label: 'Özel şirket kal',
        tradeoff: { gain: 'Esneklik ve hız', cost: 'Yatırımcılar sabırsızlanır' },
        effects: { morale: 3 },
        reflection: 'Özel kalmak, kendi saatine göre koşmaktır.',
        conceptId: 'no-single-path',
      },
    ],
  },

  // =========================================================== Kriz (3, every stage)
  {
    id: 'payroll-risk',
    stage: 0,
    category: 'crisis',
    speaker: 'accountant',
    question: 'Gelecek ayın maaşları risk altında. Nasıl ilerleyelim?',
    condition: (s) => s.stats.cash > 0 && s.finance.runway !== null && s.finance.runway < 1.5,
    weight: 3,
    once: false,
    options: [
      {
        label: 'Maaşları geçici kıs',
        tradeoff: { gain: 'Runway uzar', cost: 'Moral belirgin düşer' },
        effects: { cashPercent: 0.15, morale: -10 },
        reflection: 'Zor anda açık konuşmak, güveni korur.',
        conceptId: 'runway',
      },
      {
        label: 'Kurucu maaşından vazgeç',
        tradeoff: { gain: 'Ekip korunur', cost: 'Enerjin düşer' },
        effects: { cashPercent: 0.08, energy: -20, morale: 3 },
        reflection: 'Yükü önce kurucu taşıyınca ekip de omuz verir.',
        conceptId: 'burn',
      },
    ],
  },
  {
    id: 'vc-bridge-loan',
    stage: 1,
    category: 'crisis',
    speaker: 'investor',
    question: 'Tur bitmeden kasa bitebilir. Mevcut yatırımcı köprü kredi öneriyor.',
    condition: (s) => s.round?.active === true && s.finance.runway !== null && s.finance.runway < 2,
    weight: 3,
    options: [
      {
        label: 'Köprüyü al',
        tradeoff: { gain: 'Kasa nefes alır', cost: '%3 hisse ve borç' },
        effects: { cashPercent: 0.25, equity: -0.03, setFlag: 'bridgeLoan' },
        reflection: 'Köprü, karşıya geçmek için; üstünde yaşamak için değil.',
        conceptId: 'fundraise-time',
      },
      {
        label: 'Turu hızlandır, az al',
        tradeoff: { gain: 'Hisse korunur', cost: 'Teklif küçülür' },
        effects: { roundWeeks: -2, reputation: -3 },
        reflection: 'Az ama zamanında gelen para, çok ama geç gelenden iyidir.',
        conceptId: 'fundraise-time',
      },
    ],
  },
  {
    id: 'emergency-bridge',
    stage: 0,
    category: 'crisis',
    speaker: 'mentor',
    question: 'Kasa eksiye düştü. Birlikte bir çıkış yolu bulalım.',
    condition: (s) => s.stats.cash < 0,
    weight: 5,
    once: false,
    options: [
      {
        label: 'Acil kredi çek',
        tradeoff: { gain: 'Kasa toparlanır', cost: 'Borç ve faiz' },
        effects: { cash: 15_000, setFlag: 'emergencyLoan' },
        reflection: 'Kredi zaman satın alır; zamanı ne için kullanacağın önemli.',
        conceptId: 'runway',
      },
      {
        label: 'Kişisel birikimini koy',
        tradeoff: { gain: 'Kontrol sende', cost: 'Kişisel risk ve enerji' },
        effects: { cash: 8000, energy: -25 },
        reflection: 'Kendi parası ortada olan kurucu, her doları iki kez sayar.',
        conceptId: 'burn',
      },
    ],
  },

  // =========================================================== Rakip (3, pressure ≥ 0.35)
  {
    id: 'rival-price-war',
    stage: 2,
    category: 'rival',
    speaker: 'customer',
    question: 'Rakip fiyatını yarıya indirdi. Kullanıcılar soruyor.',
    condition: (s) => rivalPressure(s) >= 0.35,
    options: [
      {
        label: 'Fiyatı düşür',
        tradeoff: { gain: 'Kullanıcı kalır', cost: 'Gelir düşer' },
        effects: { modifiers: [mod('arpu', 0.85, 90), mod('churn', 0.9, 90)] },
        reflection: 'Fiyat savaşının kazananı genelde en derin cep olur.',
        conceptId: 'pricing',
      },
      {
        label: 'Değere odaklan',
        tradeoff: { gain: 'Marj korunur, ürün güçlenir', cost: 'Bir süre churn artar' },
        effects: { maturity: 0.04, modifiers: [mod('churn', 1.1, 45)] },
        reflection: 'Ucuz olmak yerine vazgeçilmez olmak da bir yol.',
        conceptId: 'pricing',
      },
    ],
  },
  {
    id: 'rival-talent-raid',
    stage: 2,
    category: 'rival',
    speaker: 'cofounder',
    question: 'Rakip ekibimizden iki kişiye teklif götürmüş.',
    condition: (s) => rivalPressure(s) >= 0.35 && s.derived.teamSize >= 4,
    options: [
      {
        label: 'Tutma primi ver',
        tradeoff: { gain: 'Ekip kalır', cost: 'Kasadan pay' },
        effects: { cashPercent: -0.04, morale: 5 },
        reflection: 'Prim bugünü tutar, kültür yarını.',
        conceptId: 'culture-freezes',
      },
      {
        label: 'Kültüre yatırım yap',
        tradeoff: { gain: 'Uzun vadeli bağlılık', cost: 'Kısa süre yavaşlama' },
        effects: { morale: 3, modifiers: [mod('morale', 4, 90), mod('production', 0.95, 14)] },
        reflection: 'İnsanlar şirketten çok, ekipten ayrılmakta zorlanır.',
        conceptId: 'culture-freezes',
      },
    ],
  },
  {
    id: 'rival-copycat-feature',
    stage: 2,
    category: 'rival',
    speaker: 'engineer',
    question: 'Rakip en sevilen özelliğimizi birebir kopyaladı.',
    condition: (s) => rivalPressure(s) >= 0.35,
    options: [
      {
        label: 'Hemen karşılık ver',
        tradeoff: { gain: 'Önde kalırsın', cost: 'Aceleci kod, borç' },
        effects: { maturity: 0.03, techDebt: 6, setFlag: 'rushedProject' },
        reflection: 'Rakibe koşmak, kendi yolundan sapmak olabilir.',
        conceptId: 'tech-debt',
      },
      {
        label: 'Yol haritana sadık kal',
        tradeoff: { gain: 'Tutarlı ürün, itibar', cost: 'Bir süre organik yavaşlar' },
        effects: { reputation: 3, modifiers: [mod('organic', 0.9, 30)] },
        reflection: 'Kopyalanan özellik, kopyalanamayan vizyonu gösterir.',
        conceptId: 'feature-vs-product',
      },
    ],
  },
]
