// HUD text of GAMEPLAY_V2 (docs/GAMEPLAY_V2.md §10-§14): Kazanımlar icon, center screens, strip digest.
// Spread into UI_TEXT by content/index.ts. Every new UI wording of the V2 waves lands here (strings.ts stays as is).
// Budgets (docs/VOICE.md): button ≤ 2 words, tooltip ≤ 8, empty state ≤ 4, panel sentence ≤ 12.
export const HUD_TEXT: Record<string, string> = {
  // Kazanımlar (top-bar book icon, K)
  'achv.title': 'Kazanımlar',
  'achv.open': 'Kazanımlar (K)',
  'achv.discovery': 'Keşif',

  // Guidance (§11): the step chip's count, the paused start's goal label (the number is the value)
  'step.count': '{i}/{n}',
  'start.goalLabel': '{stage} hedefi',

  // Settings > shortcuts
  'shortcut.achievements': 'Kazanımlar',
  'shortcut.stats': 'İstatistik',

  // Center screens (CenterFrame): title strip + top-bar trend icon (I)
  'center.stats': 'İstatistik',
  'center.lawbook': 'Kanun Kitabı',
  'center.market': 'Pazar haritası',
  'stats.open': 'İstatistik (I)',
  'stats.tabs': 'Sekmeler',

  // Statistics screen (§14.5): tab names, one-word chart names / axes, the one sentence (death day)
  'stats.tab.money': 'Para',
  'stats.tab.growth': 'Büyüme',
  'stats.tab.team': 'Ekip',
  'stats.tab.profile': 'Profil',
  'stats.cash': 'Kasa',
  'stats.runway': 'Runway',
  'stats.flow': 'Gelir–gider',
  'stats.revenue': 'Gelir',
  'stats.cost': 'Gider',
  'stats.split': 'Dağılım',
  'stats.mrr': 'MRR',
  'stats.users': 'Kullanıcı',
  'stats.valuation': 'Değerleme',
  'stats.target': 'Hedef',
  'stats.window': 'Pencere',
  'stats.rival': 'Rakip',
  'stats.rivalToday': '{name} · bugün',
  'stats.newUsers': 'Yeni',
  'stats.channels': 'Kanallar',
  'stats.market': 'Pazar',
  'stats.team': 'Ekip',
  'stats.morale': 'Moral',
  'stats.depts': 'Departman',
  'stats.people': 'Kişi',
  'stats.output': 'Çıktı',
  'stats.equity': 'Hisse',
  'stats.founder': 'Kurucu',
  'stats.investors': 'Yatırımcı',
  'stats.profile': 'Profil',
  'stats.company': 'Şirket',
  'stats.expected': 'Beklenti',
  'stats.other': 'Diğer',
  'stats.day': 'Gün {d}',
  'stats.deathDay': 'Kasa biter · Gün {d}',
  'stats.axis.product': 'Ürün',
  'stats.axis.growth': 'Büyüme',
  'stats.axis.efficiency': 'Verim',
  'stats.axis.team': 'Ekip',
  'stats.axis.morale': 'Moral',
  'stats.axis.cash': 'Nakit',

  // Notification strip: items folded over the daily budget (count on the ⌃ button)
  'strip.digest': '+{n}',

  // Discovery grid (§9.2, §12): seen cards over all cards, thread names, secret cell
  'codex.title': 'Keşif',
  'codex.count': '{n}/{total}',
  'codex.threads': 'İplikler',
  'codex.threadDone': 'Tamamlandı',
  'codex.secret': 'Gizli kart',
  'codex.locked': '?',
  'codex.empty': 'Henüz kart yok',
  'codex.thread.mentor': 'Mentor',
  'codex.thread.investor': 'Yatırımcı',
  'codex.thread.customer': 'Müşteri',
  'codex.thread.rival': 'Rakip',
  'codex.thread.press': 'Basın',
  'codex.step': '{n}/{total} adım',

  // Rival (§8.2, §9.4): stage-line notch, the one strip item, the market row
  'rival.unknown': 'Adsız rakip',
  'rival.notchTitle': '{name} · değerleme {v}',
  'rival.passed': '{name} seni geçti',
  'rival.share': 'Pay {p}',
  'rival.ahead': 'Önde',
  'rival.behind': 'Geride',

  // Payday desk (§6.1, §10.6): line answers, what is left after, the one sentence, commit + routine
  'desk.title': 'Maaş günü',
  'desk.line': 'Kasa bu ayı karşılamıyor; neyin bekleyeceğini sen seç.',
  'desk.short': 'Açık {v}',
  'desk.old': 'Eski borç',
  'desk.opt.full': 'Öde',
  'desk.opt.half': 'Yarı',
  'desk.opt.defer': 'Ertele',
  'desk.opt.pay': 'Öde',
  'desk.opt.cut': 'Kes',
  'desk.opt.skip': 'Atla',
  'desk.cashAfter': 'Kasa sonra',
  'desk.owedAfter': 'Borç',
  'desk.cost.morale': '{v} moral',
  'desk.cost.capacity': 'Kapasite ×{v}',
  'desk.cost.rent': 'Kira {n}/{max}',
  'desk.cost.energy': '{v} enerji',
  'desk.cost.ads': 'Reklam $0',
  'desk.cost.interest': '+{v} faiz',
  'desk.clock': 'İflas saati',
  'desk.confirm': 'Onayla',
  'desk.later': 'Sonra',
  'desk.dueTitle': 'Maaş masası: karar bekliyor',

  // Panels in the HUD grammar (§10.5): one-line rows, steps, pills
  'growth.adStep.off': '0',
  'growth.adStep.half': '½',
  'growth.adStep.same': '1×',
  'growth.adStep.double': '2×',
  'growth.row.market': 'Pazar',
  'growth.row.policies': 'Politikalar',
  'growth.row.board': 'Kurul',
  'growth.row.marketValue': '{p} · {n} segment',
  'growth.row.policiesValue': '{n} politika',
  'growth.row.policiesWait': '{n} politika · {d}g',
  'growth.row.boardValue': '{v} · {d}g',
  'shop.buyGo': 'Satın al',
  'round.mult': 'Çarpan',
  'round.multCap': 'Değerleme çarpanı',
  'round.capPill': 'Tavan',
  'round.endRunway': 'Tur sonu runway',
  'round.strikes': 'Uyarı',
  'round.downGo': 'Down round',
  'round.downTitle': 'Daha az para, daha çok hisse',
  'round.retry': '{d}g sonra',
  'round.ddMet': '+{v}',
  'round.ddMiss': '−{v}',
  'goals.prize': '−{v} hisse',
  'goals.parts': 'Değerleme',
  'goals.part.launchedN': 'Ürün {n}×{r}',
  'goals.part.usersN': 'Kullanıcı {n}×{r}',
  'goals.part.releasesN': 'Sürüm {n}/{m}×{r}',
  'projects.launchGain': '+{v}',
  'team.roughQuality': 'Tahmini verim',
  'projects.trait.time': 'Geliştirme süresi',
  'projects.trait.arpu': 'Kullanıcı başı gelir',
  'projects.trait.organic': 'Kendiliğinden yayılma',
  'goals.part.mrr': 'MRR × {x}',
  'goals.part.fade': 'Eski değer',
  'roadmap.silhouette': '?',
  'loan.title': 'Kredi',
  'loan.balance': 'Bakiye',
  'loan.rate': 'Faiz/ay',
  'loan.covenant': 'Kovenant',
  'loan.ok': 'Temiz',
  'loan.grace': 'Muaf {d}g',
  'loan.warn': 'İhlal {n} · {d}g',
  'loan.risk': 'Risk · {d}g',
  'metrics.holdTitle': 'Uzun bas: üst bara sabitle',

  // Overlays (§10.6): stage report numbers (move scene, victory), post-mortem numbers, the notebook card's fold
  'report.days': 'Gün',
  'report.goals': 'Hedef',
  'report.minRunway': 'En dar runway',
  'report.title': 'Karne',
  'report.daysShort': '{v}g',
  'move.nextOffice': 'Sonraki ofis',
  'pm.day': 'Gün',
  'pm.peakMrr': 'Zirve MRR',
  'pm.cause': 'Neden',
  'victory.codex': 'Keşif',
  'notebook.more': 'daha',
  'notebook.less': 'az',

  // Curiosity surfaces (§9.4, §5.1): the next stage's ghost, the receipt's teaser line, the covenant countdown
  'ghost.title': 'Sıradaki: {v}',
  'receipt.next': '→ {d} · {v}',
  'loan.dueTitle': 'Kovenant kontrolü {d}g',

  // Center screens' tab strip (CenterFrame): İstatistik | Kanun Kitabı | Pazar haritası
  'center.tabs': 'Ekranlar',

  // Kanun Kitabı (§7.2): tree names, lock as a number, the signing ring, the one commit, the irreversible pill
  'law.tree.survival': 'Hayatta kalma',
  'law.tree.growth': 'Büyüme',
  'law.tree.craft': 'Zanaat',
  'law.tree.org': 'Yönetim',
  'law.lock.runway': 'runway < {v}',
  'law.lock.stage': '{v}+',
  'law.lock.team': 'ekip ≥ {v}',
  'law.lock.profitMonths': 'kâr ≥ {v} ay',
  'law.lock.crisis': 'kira krizi',
  'law.signed': 'İmzalı',
  'law.closed': 'Kapalı',
  'law.count': '{n}/{total}',
  'law.wait': '{d}g',
  'law.waitTitle': 'Sıradaki imza için kalan gün',
  'law.equity': '+{v} hisse/tur',
  'law.equityTitle': 'Her turda bu kadar fazla hisse',
  'law.sign': 'İmzala',
  'law.final': 'Geri alınamaz',
  'law.pick': 'Yasa seç',

  // Pazar haritası (§8.1–8.2): segment names, fill ring, open commit, rival rows, buy commit
  'mkt.segment.early': 'Erken',
  'mkt.segment.smb': 'KOBİ',
  'mkt.segment.midmarket': 'Orta pazar',
  'mkt.segment.enterprise': 'Kurumsal',
  'mkt.segment.global': 'Küresel',
  'mkt.fill': 'Doluluk',
  'mkt.size': '{v} kişi',
  'mkt.upkeep': '{v}/ay',
  'mkt.open': 'Aç',
  'mkt.auto': 'Otomatik',
  'mkt.rivals': 'Rakipler',
  'mkt.you': 'Sen',
  'mkt.brings': '+{v} kullanıcı',
  'mkt.buy': 'Satın al',
  'mkt.lead': 'Baş rakip',
  'mkt.rivalsEmpty': 'Rakip yok',
  'mkt.full': 'Pazar doluyor; büyümek için yeni segment aç.',

  // Kurul (§8.3) and renewals (§8.4) in Büyüme
  'board.title': 'Kurul',
  'board.missed': 'Kaçan {n}',
  'board.streak': 'Seri {n}',
  'board.penalty': 'Çarpan ×{v}',
  'board.progressTitle': 'MRR, kurul hedefine göre',
  'renew.title': 'Yenileme',
  'renew.hold': 'Zam iste',
  'renew.discount': 'İndirim ver',
  'renew.chance': 'Şans {p}',
  'renew.fail': 'Kayıp {p}',
  'renew.days': '{d}g',

  // Loan offer on a decision card (§6.2): amount, rate, term, covenant as numbers
  'loan.amount': 'Tutar',
  'loan.term': 'Vade',

  // Dock: a late tool not open yet (grey silhouette + its stage)
  'dock.lockedTitle': '{tool} · {stage}',

  // Stats (§14.5): the two late cost slices, the lead rival's line
  'burn.expansion': 'Pazar',
  'burn.interest': 'Faiz',

  // The sale (acquired, §8.2): three numbers + XP + "Yeniden"
  'acq.valuation': 'Satış değeri',
  'acq.equity': 'Payın',
  'acq.day': 'Gün',
}
