// Keyed Turkish UI text. Typed tables for id-based lookups + one flat UI_TEXT dictionary (key → text, {param}).
// Components never hardcode Turkish strings; they call t('key') over UI_TEXT.
import type {
  ActionErrorCode,
  Archetype,
  ConceptId,
  EmployeeStatus,
  FounderActionKind,
  HudWidget,
  MilestoneId,
  PostMortemCode,
  SlotType,
  ToolId,
} from '../engine/types'
import type { DecisionCategory } from './types'
import { STAGES } from './stages'
import { DEPT_TEXT, PROJECT_CATEGORY_TEXT } from './text'

export const FOUNDER_ACTION_TEXT: Record<FounderActionKind, { name: string; description: string }> = {
  findUsers: { name: 'Elle kullanıcı bul', description: '1 gün sürer, birkaç sadık kullanıcı getirir.' },
  talkToUsers: { name: 'Kullanıcıyla konuş', description: 'Seçili projenin olgunluğunu artırır.' },
  motivateTeam: { name: 'Ekibi motive et', description: 'Kısa süreli moral, senin enerjinden.' },
  investorCoffee: { name: 'Yatırımcıyla kahve', description: 'Yatırım turunu kısaltır.' },
  salesCall: { name: 'Satış görüşmesi', description: 'Tek bir büyük müşteri kazandırabilir.' },
  rest: { name: 'Dinlen', description: 'Enerjini toplar, şirket kısa süre sensiz döner.' },
}

export const ARCHETYPE_TEXT: Record<Archetype, { name: string; description: string }> = {
  bootstrap: { name: 'Bootstrap', description: 'Az yatırım, erken kâr, sağlam adımlar.' },
  vcRocket: { name: 'VC-Roket', description: 'Büyük turlar, hızlı büyüme, yüksek tempo.' },
  niche: { name: 'Niş Uzman', description: 'Dar bir kitle, derin bir ürün, sadık kullanıcı.' },
  platform: { name: 'Platform', description: 'Geniş pazar, çok ürün, ağ etkisi.' },
}

export const HUD_WIDGET_TEXT: Record<HudWidget, string> = {
  cash: 'Kasa',
  users: 'Kullanıcı',
  morale: 'Moral',
  runway: 'Runway',
  burnBreakdown: 'Gider kırılımı',
  retention: 'Tutunma',
  profitProjection: 'Kâr projeksiyonu',
  capTable: 'Cap table',
  roundTimer: 'Tur süresi',
  candidateQuality: 'Aday kalitesi',
  moraleHeatmap: 'Moral haritası',
  churn: 'Churn',
  arpu: 'ARPU',
  reputation: 'İtibar',
  equity: 'Kurucu kontrolü',
  ltvCac: 'LTV:CAC',
  channelBreakdown: 'Kanal kırılımı',
  debtCounter: 'Teknik borç',
  coordinationWarning: 'Koordinasyon',
  cultureBadge: 'Kültür rozeti',
  revenueDistribution: 'Gelir dağılımı',
  archetypeBadge: 'Arketip rozeti',
}

export const TOOL_TEXT: Record<ToolId, { name: string; description: string }> = {
  priceControl: { name: 'Fiyat ayarı', description: 'Kullanıcı başı fiyatı belirle.' },
  adBudget: { name: 'Reklam bütçesi', description: 'Aylık reklam harcamasını ayarla.' },
  enterpriseSales: { name: 'Kurumsal satış', description: 'Büyük müşterilerle sözleşme yap.' },
  capTableView: { name: 'Cap table', description: 'Şirketin kimde ne kadar olduğunu gör.' },
}

export const SLOT_TYPE_TEXT: Record<SlotType, { name: string; description: string }> = {
  desk: { name: 'Masa', description: 'Bir çalışan oturur.' },
  common: { name: 'Ortak alan', description: 'Komşu masalara moral verir.' },
  room: { name: 'Oda', description: 'İki slot kaplar, tüm şirkete etki eder.' },
  special: { name: 'Özel', description: 'Aşama ödülü, itibar ve özel güç.' },
}

export const EMPLOYEE_STATUS_TEXT: Record<EmployeeStatus, string> = {
  working: 'Çalışıyor',
  tired: 'Yorgun',
  burnout: 'Tükenmiş',
  break: 'Molada',
  onboarding: 'Yeni',
  leaving: 'Ayrılmak üzere',
}

export const MILESTONE_TEXT: Record<MilestoneId, string> = {
  users100: 'İlk 100 kullanıcı!',
  users1000: '1.000 kullanıcı!',
  users10k: '10.000 kullanıcı!',
  firstMrr: 'İlk gelir geldi!',
  firstProfitMonth: 'İlk kârlı ay!',
  firstLaunch: 'İlk ürün yayında!',
}

export const ACTION_ERROR_TEXT: Record<ActionErrorCode, string> = {
  insufficientCash: 'Kasada yeterli para yok.',
  noFreeSlot: 'Boş slot kalmadı.',
  slotOccupied: 'Bu slot dolu.',
  slotLocked: 'Bu halka henüz kilitli.',
  wrongSlotType: 'Bu eşya bu slota uymuyor.',
  ringOrder: 'Önce içteki halkayı açmalısın.',
  noDesk: 'Önce boş bir slota masa koy.',
  notUnlocked: 'Bu henüz açılmadı.',
  cooldown: 'Biraz beklemen gerekiyor.',
  noEnergy: 'Enerjin yetmiyor, biraz dinlen.',
  founderBusy: 'Şu an başka bir işle meşgulsün.',
  notFound: 'Bulunamadı.',
  roundActive: 'Zaten süren bir tur var.',
  roundNotReady: 'Değerleme hedefe henüz ulaşmadı.',
  gameOver: 'Oyun bitti.',
  invalid: 'Bu işlem yapılamıyor.',
  engineNotConnected: 'Motor henüz bağlı değil.',
}

export const DECISION_CATEGORY_TEXT: Record<DecisionCategory, string> = {
  normal: 'Karar',
  crisis: 'Kriz',
  rival: 'Rakip',
}

/** Post-mortem reason headings (body text lives in POST_MORTEM_TEXT). */
export const POST_MORTEM_TITLE: Record<PostMortemCode, string> = {
  runwayIgnored: 'Tur geç başladı',
  burnTooHigh: 'Yakıt çok yüksekti',
  scaledWithoutPmf: 'Uyum gelmeden ölçeklendi',
  highChurn: 'Kullanıcılar kalmadı',
  lowMorale: 'Ekip yoruldu',
  prematureScaling: 'Ekip erken büyüdü',
  lateFundraise: 'Para yetişmedi',
  overload: 'Altyapı yetişmedi',
  teamLost: 'Ekip dağıldı',
  unfocused: 'Odak dağıldı',
}

/** Short Defter titles for each concept. */
export const CONCEPT_TITLE: Record<ConceptId, string> = {
  runway: 'Runway',
  burn: 'Burn',
  'dont-scale': 'Ölçeklenmeyen işler',
  pmf: 'Ürün-pazar uyumu',
  focus: 'Odak',
  'default-alive': 'Default-alive',
  dilution: 'Dilution',
  safe: 'SAFE',
  'fundraise-time': 'Tur zaman alır',
  'hire-bar': 'İşe alım çıtası',
  'morale-compounds': 'Moral bileşiktir',
  churn: 'Churn',
  pricing: 'Fiyatlama',
  'feature-vs-product': 'Özellik mi ürün mü',
  'premature-scaling': 'Erken ölçekleme',
  'ltv-cac': 'LTV:CAC',
  'organic-vs-paid': 'Organik ve ücretli',
  'tech-debt': 'Teknik borç',
  'ten-x-myth': '10x efsanesi',
  'culture-freezes': 'Kültür donar',
  concentration: 'Yoğunlaşma riski',
  compliance: 'Uyum',
  trough: 'Hayal kırıklığı vadisi',
  'cap-table-health': 'Cap table sağlığı',
  'no-single-path': 'Tek yol yok',
  'founder-burnout': 'Kurucu tükenmişliği',
  'failure-is-data': 'Başarısızlık veridir',
}

const BASE_TEXT: Record<string, string> = {
  'app.title': 'Be Unicorn',
  'app.tagline': 'Garajdan unicorn’a.',

  // Common buttons
  'common.close': 'Kapat',
  'common.ok': 'Tamam',
  'common.cancel': 'Vazgeç',
  'common.confirm': 'Onayla',
  'common.back': 'Geri',
  'common.continue': 'Devam',
  'common.buy': 'Satın al',
  'common.sell': 'Sat',
  'common.move': 'Taşı',
  'common.upgrade': 'Yükselt',
  'common.hire': 'İşe al',
  'common.fire': 'Çıkar',
  'common.locked': 'Kilitli',
  'common.free': 'Ücretsiz',
  'common.newGame': 'Yeni oyun',
  'common.continueGame': 'Devam et',
  'common.save': 'Kaydet',

  // HUD
  'hud.cash': 'Kasa',
  'hud.cashTitle': 'Kasa ve aylık net',
  'hud.users': 'Kullanıcı',
  'hud.morale': 'Moral',
  'hud.runway': 'Runway',
  'hud.burn': 'Yakıt',
  'hud.monthly': 'Aylık',
  'hud.perMonth': '{v}/ay',
  'hud.perMonthPlain': '{v}/ay',
  'hud.perUser': 'kullanıcı başı',
  'hud.date': 'Ay {m} · Gün {d}',
  'hud.stage': 'Aşama',
  'hud.stageProgressTitle': '{stage} hedefine ilerleme',
  'hud.more': 'Daha fazla gösterge',
  'hud.retention': 'Tutunma',
  'hud.profitProjection': 'Kâr projeksiyonu',
  'hud.profitable': 'Kârdasın',
  'hud.gap': 'Kâra {v} kaldı',
  'hud.capTable': 'Cap table',
  'hud.yours': 'senin payın',
  'hud.equity': 'Hisse',
  'hud.roundTimer': 'Tur',
  'hud.churn': 'Churn',
  'hud.arpu': 'ARPU',
  'hud.reputation': 'İtibar',
  'hud.ltvCac': 'LTV:CAC',
  'hud.ltvLow': 'Reklam para yakıyor',
  'hud.ltvOk': 'Reklam kendini ödüyor',
  'hud.channels': 'Kanallar',
  'hud.techDebt': 'Teknik borç',
  'hud.debtTitle': 'Borç: {v}',
  'hud.coordination': 'Koordinasyon',
  'hud.output': 'verim kaybı',
  'hud.coordinationOk': 'Sorun yok',
  'hud.coordinationOkSub': '6 kişiye kadar',
  'hud.noRound': 'Tur yok',
  'hud.archetypeUnknown': 'Henüz belirsiz',
  'hud.moraleMap': 'Moral haritası',
  'hud.moraleMapValue': '{low} düşük · {mid} yorgun · {high} iyi',
  'hud.control': 'Kontrol sende',
  'hud.controlShared': 'Kontrol paylaşımlı',
  'hud.culture': 'Kültür',
  'hud.cultureValue': '{n} kişilik ekip',
  'hud.revenueDist': 'Gelir dağılımı',
  'hud.topCustomer': 'En büyük müşteri {v}',
  'hud.selfServe': 'Bireysel',
  'hud.archetype': 'Yolun',
  'hud.overload': 'Aşırı yük',

  // Speed & view
  'speed.label': 'Hız',
  'speed.hint': '{v}× hız',
  'speed.pauseHint': 'Duraklat',
  'speed.pause': 'Duraklat',
  'speed.play': 'Devam',
  'view.zoomIn': 'Yakınlaştır',
  'view.zoomOut': 'Uzaklaştır',
  'view.soundOn': 'Sesi aç',
  'view.soundOff': 'Sesi kapat',
  'view.language': 'Dil',
  'view.languageSoon': 'Yakında başka diller de gelecek.',
  'view.screenshot': 'Ekran görüntüsü',
  'view.settings': 'Ayarlar',
  'settings.title': 'Ayarlar',

  // Dock
  'dock.label': 'Ana menü',
  'dock.shop': 'Mağaza',
  'dock.team': 'Ekip',
  'dock.projects': 'Projeler',
  'dock.growth': 'Büyüme',
  'dock.journal': 'Defter',

  // Shop
  'shop.all': 'Tümü',
  'shop.catalog': 'Katalog',
  'shop.empty': 'Bu kategoride henüz eşya yok.',
  'shop.expand': 'Ofisi büyüt',
  'shop.openRing': 'Halkayı aç',
  'shop.ringTitle': '{n}. halka',
  'shop.ringCost': 'Açma bedeli {cost}',
  'shop.ringRent': 'Kira +{v}/ay',
  'shop.ringsOpen': '{n}/{total} halka açık',
  'shop.allRingsOpen': 'Tüm halkalar açık.',
  'shop.slotLocked': '{stage} aşamasında açılır',
  'shop.upkeep': 'Bakım {v}/ay',
  'shop.autoHint': 'Satın aldığın eşya merkeze en yakın boş yere konur. Yerini sonra "Taşı" ile değiştirebilirsin.',
  'shop.forSlot': '{ring}. halka · {type} slotu için',
  'shop.clearTarget': 'Filtreyi kaldır',
  'shop.bought': '{item} yerleştirildi ({ring}. halka)',
  'shop.noRoom': 'Boş yer yok',
  'shop.noRoomOpenRing': 'Boş yer yok — {n}. halkayı aç ({cost})',
  'shop.noRoomNextStage': 'Boş yer yok. Sonraki ofiste daha çok yer var.',
  'shop.roomInRing': 'Bu eşyaya {ring}. halkada yer var (halkalar sırayla açılır).',
  'shop.targetMisfit': 'Bu slota sığmaz → {ring}. halkaya konur',
  'shop.targetMisfitNoRoom': 'Bu slota sığmaz',
  'panel.label': 'Panel',
  'shop.price': 'Fiyat',

  // Effects (shop / detail panel)
  'effect.moraleAura': 'Komşu masalara +{v} moral',
  'effect.deskQuality': 'Verim ×{v}',
  'effect.deptBonus': '{dept} verimi +{v}',
  'effect.capacity': 'Kapasite ×{v}',
  'effect.infra': 'Altyapı gideri ×{v}',
  'effect.coordinationFix': 'Koordinasyon cezasını kaldırır',
  'effect.globalMorale': 'Tüm ekibe +{v} moral',
  'effect.reputation': '+{v} itibar',
  'effect.maturity': 'Ürün gelişimi +{v}',
  'effect.enables': '{tool} açar',

  // Team
  'team.members': 'Ekip ({n})',
  'team.candidates': 'Adaylar',
  'team.empty': 'Henüz ekip yok. İlk kişiyi işe al!',
  'team.noCandidates': 'Şu an aday yok.',
  'team.refresh': 'Yeni adaylar',
  'team.hire': 'İşe al',
  'team.fire': 'Yollarınızı ayır',
  'team.expires': '{n} gün içinde gider',
  'team.freeDesks': '{n} boş masa',
  'team.noDesk': 'Masası yok',
  'team.needDeskItem': 'Boş masa yok: önce bir slota masa koy',
  'team.noSlot': 'Boş slot yok: yeni halka aç',
  'team.noSeat': 'Önce bir masa yerleştir.',
  'team.salary': 'Maaş',
  'team.quality': 'Kalite',
  'team.dept': 'Departman',
  'team.leavingIn': '{n} gün içinde ayrılıyor',
  'team.raise': 'Zam yap',
  'team.talk': 'Konuş',
  'team.letGo': 'Bırak gitsin',
  'team.seat': 'Masaya oturt',

  // Projects
  'projects.active': 'Projeler',
  'projects.new': 'Yeni proje',
  'projects.start': 'Başlat',
  'projects.empty': 'Henüz proje yok. Bir kategori seç ve başla.',
  'projects.assign': 'Ata',
  'projects.assigned': '{n} kişi',
  'projects.building': 'Geliştiriliyor',
  'projects.live': 'Yayında',
  'projects.maturity': 'Olgunluk',

  // Growth
  'growth.product': 'Ürün',
  'growth.avgMaturity': 'Ortalama olgunluk',
  'growth.liveProjects': 'Yayındaki projeler',
  'growth.capacity': 'Kapasite',
  'growth.channels': 'Kanallar',
  'growth.mrr': 'Aylık gelir (MRR)',
  'growth.mom': 'Aylık büyüme {v}',
  'growth.adBudget': 'Reklam bütçesi',
  'growth.adLocked': 'Reklam bütçesi Series A’da açılır.',
  'growth.cac': 'Kullanıcı edinme maliyeti',
  'growth.paidUsers': 'Reklamdan gelen',
  'growth.price': 'Fiyat',
  'growth.priceMultiplier': 'Fiyat çarpanı',
  'growth.priceLocked': 'Fiyat ayarı Seed’de açılır.',
  'growth.priceWarning': 'Zam, bir ay boyunca churn’ü artırır.',
  'growth.arpuNow': 'Kullanıcı başı {v}/ay',
  'growth.enterprise': 'Kurumsal müşteriler',
  'growth.enterpriseEmpty': 'Henüz kurumsal müşteri yok.',
  'growth.enterpriseLocked': 'Kurumsal satış Series B’de açılır.',

  // Channels & burn breakdown
  'channel.organic': 'Organik',
  'channel.paid': 'Reklam',
  'channel.manual': 'Elle',
  'channel.enterprise': 'Kurumsal',
  'burn.salaries': 'Maaşlar',
  'burn.rent': 'Kira',
  'burn.infra': 'Altyapı',
  'burn.ads': 'Reklam',

  // Journal (Defter)
  'journal.title': 'Kurucu Defteri',
  'journal.what': 'Ne?',
  'journal.where': 'Sen nerede gördün?',
  'journal.rule': 'Kural',
  'journal.count': '{n}/{total} ders',
  'journal.empty': 'Defterin henüz boş. Ofiste konuşulanlara kulak ver.',
  'journal.shelf': 'Kitaplık',
  'journal.cardLabel': 'Defter kartı',
  'journal.gotIt': 'Anladım',
  'journal.unlocked': 'Açıldı: {v}',
  'journal.waiting': 'Henüz keşfedilmedi',
  'journal.missing': 'Kart bulunamadı ({id})',

  // Bubbles & decisions
  'bubble.openNotebook': 'Deftere bak',
  'bubble.collapse': 'Küçült',
  'decision.title': 'Karar',
  'decision.gain': 'Kazanç',
  'decision.cost': 'Bedel',
  'decision.youChose': 'Seçimin: {v}',
  'decision.notebookLink': 'Defter: {v}',
  'decision.reflection': 'Yansıma',

  // Founder
  'founder.you': 'Sen',
  'founder.energy': 'Enerji',
  'founder.actions': 'Kurucu aksiyonları',
  'founder.busy': 'Şu an: {action}',
  'founder.lockedAt': '{action} {stage} aşamasında açılır',
  'founder.cooldown': '{action} {d} gün sonra hazır',
  'founder.noEnergy': '{action}: enerjin yetmiyor, önce dinlen',
  'founder.noProject': '{action}: önce bir proje başlat',
  'founder.short.findUsers': 'Kullanıcı',
  'founder.short.talkToUsers': 'Konuş',
  'founder.short.motivateTeam': 'Motive',
  'founder.short.investorCoffee': 'Kahve',
  'founder.short.salesCall': 'Satış',
  'founder.short.rest': 'Dinlen',

  // Round
  'round.start': 'Tur başlat',
  'round.title': 'Yatırım turu',
  'round.offer': 'Teklif: {amount} karşılığı {equity}',
  'round.inProgress': 'Tur görüşmesi sürüyor',
  'round.inProgressShort': 'Tur: {v} hafta',
  'round.notReady': 'Değerleme hedefe ulaşınca açılır.',
  'round.closed': 'Tur kapandı!',
  'round.moveTitle': 'Yeni ofise taşınıyoruz',
  'round.moveBody': 'Mobilyalar yeni ofise bedava taşındı.',

  // Units
  'unit.months': '{v} ay',
  'unit.weeksLeft': '{v} hafta kaldı',
  'unit.days': '{v} gün',
  'unit.infinite': 'sonsuz',
  'activity.day': 'Gün {d}',

  // Game over
  'gameOver.bankruptTitle': 'Şirket kapandı',
  'gameOver.bankruptBody': 'Kasa 60 gün ekside kaldı.',
  'gameOver.teamLostTitle': 'Ekip dağıldı',
  'gameOver.teamLostBody': 'Şirkette kimse kalmadı.',
  'gameOver.reasonsTitle': 'Post-mortem: üç kör nokta',
  'gameOver.xp': '+{v} Kurucu XP',
  'gameOver.xpHint': 'Sonraki oyunda başlangıç kasan %{v} daha fazla.',
  'gameOver.retry': 'Yeniden kur',
  'victory.title': 'Unicorn oldun!',
  'victory.body': 'Garajdan bir milyar dolara. {days} günde.',
  'victory.lessons': '{n} ders öğrendin.',

  // Detail panel, placing, round/move/post-mortem/victory overlays, settings
  'common.later': 'Sonra',
  'decision.expired': 'Bu karar artık masada değil.',
  'detail.founderDesk': 'Kurucu masası',
  'detail.emptySlot': 'Boş slot',
  'detail.slotSub': '{type} · {ring}. halka',
  'detail.founderSub': 'Kurucu',
  'detail.gone': 'Bu artık burada değil.',
  'detail.ringLocked': '{n}. halka henüz kilitli.',
  'detail.ringFirst': 'Önce {n}. halkayı açmalısın.',
  'detail.occupant': 'Oturan',
  'detail.founderSeat': 'Burası senin masan.',
  'detail.seatHere': 'Buraya oturt',
  'detail.freeDesk': 'Masa boş. İşe alınca biri oturur.',
  'detail.needDesk': 'Önce bir masa yerleştir.',
  'detail.upgrade': '{item} ({v})',
  'detail.move': 'Taşı',
  'detail.sell': 'Sat',
  'detail.sellConfirm': 'Emin misin? Sat',
  'detail.salary': 'Maaş',
  'detail.quality': 'Kalite',
  'detail.desk': 'Masa',
  'detail.seated': 'Oturuyor',
  'detail.project': 'Proje',
  'detail.changeDesk': 'Masasını değiştir',
  'detail.pickDesk': 'Masa seç',
  'detail.fire': 'Yollarınızı ayır',
  'detail.fireConfirm': '{name} gitsin mi? Onayla',
  'detail.maturity': 'Olgunluk',
  'detail.launched': 'Yayında. Olgunlaştıkça daha çok değer üretir.',
  'detail.mvpHint': 'Olgunluk {v} olunca MVP yayına çıkar.',
  'detail.team': 'Ekip',
  'detail.size': 'Büyüklük',
  'detail.doing': 'Şu an',
  'detail.idle': 'Ofiste',
  'detail.xp': 'Kurucu XP',
  'placing.move': 'Taşımak için boş bir slot seç',
  'placing.seat': '{name} için boş bir masa seç',
  'round.confirmTitle': '{stage} turu',
  'round.confirmSub': 'Yatırımcılarla görüşmeler başlasın mı?',
  'round.activeTitle': 'Tur görüşmesi sürüyor',
  'round.activeSub': 'Metriklerin güçlü kalırsa teklif de güçlü kalır.',
  'round.progress': 'İlerleme',
  'round.weeks': '{done}/{total} hafta',
  'round.amount': 'Tutar',
  'round.equitySold': 'Satılan hisse',
  'round.preMoney': 'Ön değerleme',
  'round.valuationNow': 'Şu anki değerleme',
  'round.yourEquity': 'Senin hissen',
  'round.takesWeeks': 'Tur 4–8 hafta sürer, kasa beklemez.',
  'round.metricsMatter': 'Görüşmeler sürerken metrikler düşerse teklif küçülür.',
  'round.runwayNow': 'Şu anki runway: {v} ay.',
  'round.coffeeHint': 'Yatırımcıyla kahve içmek turu kısaltır.',
  'move.kicker': 'Yeni aşama: {stage}',
  'move.from': 'Eski ofis: {office}',
  'move.unlocks': 'Açılan yeni şey',
  'move.go': 'Yeni ofise geç',
  'pm.sub': '{stage} · {m}. ay',
  'pm.yourNumber': 'Senin sayın: {v}',
  'pm.xpHint': 'Toplam Kurucu XP: {total}. Sonraki şirket biraz daha güçlü başlar.',
  'pm.failureIsData': 'Bu bir veri noktası, kimlik değil.',
  'victory.kicker': '1 milyar dolar',
  'victory.valuation': 'Değerleme',
  'victory.team': 'Ekip',
  'victory.learned': 'Öğrenilen ders',
  'victory.archetype': 'Yolun: {v}',
  'victory.again': 'Yeni bir şirket kur',
  'settings.language': 'Dil',
  'settings.sound': 'Ses',
  'settings.screenBubbles': 'Ofis sohbetlerini göster',
  'settings.zoom': 'Yakınlık',
  'settings.save': 'Kaydet',
  'settings.load': 'Kayıttan yükle',
  'settings.saved': 'Kaydedildi.',
  'settings.loaded': 'Kayıt yüklendi.',
  'settings.noSave': 'Uyumlu bir kayıt bulunamadı.',
  'settings.newGame': 'Yeni oyun',
  'settings.newGameConfirm': 'Bu oyun silinsin mi? Onayla',
  'settings.shortcuts': 'Klavye kısayolları',
  'unit.people': '{v} kişi',
  'unit.projects': '{v} proje',
  'visitor.decision': 'Seninle bir konu konuşmaya geldi.',
  'visitor.concept': 'Bir şey anlatmak istiyor.',
  'visitor.round': 'Yatırım görüşmesi için burada.',
  'visitor.ambient': 'Ofise uğradı.',
  'shortcut.pause': 'Duraklat / devam',
  'shortcut.speed': 'Hız 1× / 2× / 4×',
  'shortcut.tabs': 'Mağaza · Ekip · Projeler · Büyüme · Defter',
  'shortcut.escape': 'İptal / kapat',
  'shortcut.zoom': 'Yakınlaştır / uzaklaştır',
  'zoom.0': 'Uzak',
  'zoom.1': 'Normal',
  'zoom.2': 'Yakın',
  'start.title': 'Be Unicorn',
  'start.tagline': 'Garajdan kampüse: bir startup kur, 1 milyar dolara ulaş.',
  'start.new': 'Yeni oyun',
  'start.continue': 'Devam et',
  'start.continueSub': '{stage} · {day}. gün',
  'start.xp': 'Founder XP: {v}',
  'start.xpBonus': 'Başlangıç kasası +%{v}',
  'start.noXp': 'İlk girişim. Batarsan XP kazanırsın.',
  'start.hint': 'Masaüstünde en iyi deneyim. Dokunmatikte de oynanır.',
}

function prefixed<K extends string>(prefix: string, table: Record<K, string | { name: string }>): Record<string, string> {
  const out: Record<string, string> = {}
  for (const [k, v] of Object.entries(table) as [K, string | { name: string }][]) {
    out[`${prefix}.${k}`] = typeof v === 'string' ? v : v.name
  }
  return out
}

function descriptions<K extends string>(prefix: string, table: Record<K, { description: string }>): Record<string, string> {
  const out: Record<string, string> = {}
  for (const [k, v] of Object.entries(table) as [K, { description: string }][]) out[`${prefix}.${k}.desc`] = v.description
  return out
}

export const UI_TEXT: Record<string, string> = {
  ...BASE_TEXT,
  ...prefixed('founder', FOUNDER_ACTION_TEXT),
  ...descriptions('founder', FOUNDER_ACTION_TEXT),
  ...prefixed('archetype', ARCHETYPE_TEXT),
  ...descriptions('archetype', ARCHETYPE_TEXT),
  ...prefixed('widget', HUD_WIDGET_TEXT),
  ...prefixed('tool', TOOL_TEXT),
  ...descriptions('tool', TOOL_TEXT),
  ...prefixed('slot', SLOT_TYPE_TEXT),
  ...descriptions('slot', SLOT_TYPE_TEXT),
  ...prefixed('status', EMPLOYEE_STATUS_TEXT),
  ...prefixed('milestone', MILESTONE_TEXT),
  ...prefixed('error', ACTION_ERROR_TEXT),
  ...prefixed('decisionCategory', DECISION_CATEGORY_TEXT),
  ...prefixed('concept', CONCEPT_TITLE),
  ...prefixed('postMortem', POST_MORTEM_TITLE),
  ...prefixed('dept', DEPT_TEXT),
  ...prefixed('category', PROJECT_CATEGORY_TEXT),
  ...Object.fromEntries(STAGES.map((st) => [`stage.${st.key}`, st.name])),
  ...Object.fromEntries(STAGES.map((st) => [`office.${st.key}`, st.officeName])),
}
